'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { GoogleOAuthProvider } from '@react-oauth/google';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId='916629565001-ni2k1q0n3ovmd2djapc4phi297o3rfue.apps.googleusercontent.com'>
          {children}
        </GoogleOAuthProvider>
        </body>
    </html>
  )
}
